@startuml


entity "User"{
  *id : number <<generated>>
  --
  *name : text
  *passoword : text
}

entity "Post"{
  *id : number <<generated>>
  --
  *user_id : number <<FK>>
  *src : text
  *idade:
  *peso:
  *title: text
}

entity "Comments"{
  *user_id : number <<FK>>
  *post_id : number <<FK>>
  --
  *comment : text
}

User }o-- Post
Post }o--right Comments



@enduml
